blank_issues_enabled: false  # trueã«ã™ã‚‹ã¨ã€Œãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã‚’ä½¿ã‚ãªã„ç©ºissueã€ã‚’è¨±å¯ã™ã‚‹
contact_links:               # ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆä»¥å¤–ã®å•ã„åˆã‚ã›å…ˆã‚’æ¡ˆå†…ã§ãã‚‹
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’èª­ã‚€
    url: https://github.com/disrupt-infocom/infocom-docs/wiki
    about: ä¸æ˜ç‚¹ãŒã‚ã‚‹å ´åˆã¯ã¾ãšã¯ã“ã¡ã‚‰ã‚’å‚ç…§ã—ã¦ãã ã•ã„